polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls_app.urls')),
]

polls_app/urls.py
from django.urls import path
from polls_app import views


app_name = "polls_app"
urlpatterns = [
    path('', views.IndexView.as_view(), name="base-view" ),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('<int:pk>/results/', views.ResultsView.as_view(), name="results"),
    path('<int:question_id>/vote/', views.vote, name="vote"),
]

# urlpatterns = [
#     path('', views.index, name="base-view" ),
#     path('<int:question_id>/', views.detail, name="detail"),
#     path('<int:question_id>/results/', views.results, name="results"),
#     path('<int:question_id>/vote/', views.vote, name="vote"),
# ]

polls_app/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date-published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    
class Choices(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="question_choies")
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls_app/views.py
from django.shortcuts import render
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choices
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse
from django.utils import timezone
from django.db.models import Q

# Create your views here.
# class CustomGenericeViewSet(generic.ListView, generic.CreateView, generic.UpdateView, generic.DeleteView):
#     pass 

class IndexView(generic.ListView):
    template_name = "polls_app/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.filter(
            question_choies__isnull=False,
            pub_date__lte=timezone.now(),
            ).distinct().order_by("pub_date")[:5]
        #  return Question.objects.filter(
        #     pub_date__lte=timezone.now(),
        #     ).order_by("pub_date")

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls_app/detail.html"

    def get_queryset(self):
        return Question.objects.filter(
            question_choies__isnull = False,
            pub_date__lte = timezone.now()).distinct()

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls_app/results.html"

    def get_queryset(self):
        return Question.objects.filter(
            question_choies__isnull = False,
            pub_date__lte = timezone.now()).distinct()


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.question_choies.get(pk=request.POST["choice"])
    except (KeyError, Choices.DoesNotExist):
        return render(
            request,
            "polls_app/detail.html",
            {
                "question": question,
                "error_message": "Your didn't select a choice."
            },
        )
    else:
        selected_choice.votes = F("votes")+1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls_app:results", args=(question.id,)))





# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     context = {
#         "latest_question_list": latest_question_list,
#     }
#     # output = ",".join([q.question_text for q in latest_question_list])
#     return render(request, "polls_app/index.html", context)

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls_app/detail.html", {'question':question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls_app/results.html", {"question": question})

# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choices_set.get(pk=request.POST["choice"])
#     except (KeyError, Choices.DoesNotExist):
#         return render(
#             request,
#             "polls_app/detail.html",
#             {
#                 "question": question,
#                 "error_message": "Your didn't select a choice."
#             },
#         )
#     else:
#         selected_choice.votes = F("votes")+1
#         selected_choice.save()
#         return HttpResponseRedirect(reverse("polls_app:results", args=(question.id,)))

polls_app/templates/polls_app/detail.html
<form action="{% url 'polls_app:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.question_choies.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls_app/templates/polls_app/index.html
{% load static%}
<link rel="stylesheet" href="{%static 'polls_app/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls_app:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls_app/templates/polls_app/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.question_choies.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls_app:detail' question.id %}">Vote again?</a>